In [ ]:
import numpy as np
from pyqpanda import * 

In [10]:
qvm = CPUQVM()
qvm.init_qvm()
q = qvm.qAlloc_many(2)
prog = QProg()
prog << CNOT(q[0],q[1])

mat = get_unitary(prog)
print(mat)

d = np.array(mat)

[(1+0j), 0j, 0j, 0j, 0j, 0j, 0j, (1+0j), 0j, 0j, (1+0j), 0j, 0j, (1+0j), 0j, 0j]


In [ ]:
d = np.load('Hamiltonian_matrix.npy')
np.li

(16, 16)

In [14]:
complex(2.0,1.6)

(2+1.6j)

In [1]:
qvm = CPUQVM()
qvm.init_qvm()

qubits = qvm.qAlloc_many(2)
cbits = qvm.cAlloc_many(2)

# 构建量子程序
prog = QProg()
circuit = QCircuit()

circuit << H(qubits[0])

prog << circuit << Measure(qubits[0], cbits[0]) << Measure(qubits[1], cbits[1])

# 量子程序运行1000次，并返回测量结果
result = qvm.run_with_configuration(prog, cbits, 1000)

# 打印量子态在量子程序多次运行结果中出现的次数
print(result)

NameError: name 'CPUQVM' is not defined

In [4]:
A = np.array([[1.0,1],[1,-1]]) / np.sqrt(2)
b = np.array([1.0/4,-1/2]) * np.sqrt(2)

np.linalg.solve(A,b)

array([-0.25,  0.75])

In [5]:
np.linalg.eig(A)

(array([ 1., -1.]),
 array([[ 0.92387953, -0.38268343],
        [ 0.38268343,  0.92387953]]))

In [4]:
np.linalg.norm(np.array([1.125,0.375]))

1.1858541225631423

In [10]:
a = np.array(1+1j)
a*a.conjugate()

(2+0j)

In [33]:
# A = np.array([[1.0, -1/3],[-1/3, 1]])
b = np.array([-1.0/2, 5.0/6])
norm_b = np.linalg.norm(b)
print(norm_b)
b_norm = b / norm_b
print(b_norm, b_norm.T @ b_norm)
theta = np.arccos(b_norm[0])
print(np.array([np.cos(theta),np.sin(theta)]))
np.tr

0.9718253158075502
[-0.51449576  0.85749293] 1.0
[-0.51449576  0.85749293]


In [9]:
data = {
"" : -1.628013,
"X0 X1 X3 Z4 Z5 Z6 Z7 Z8 Z9 X10" : -0.000020,
"X0 X1 Y10 Y11" : -0.020966,
"X0 X1 Y2 Y3" : -0.030795,
"X0 X1 Y2 Z3 Z4 Z5 Z6 Z7 Z8 Z9 Z10 Y11" : -0.000020,
"X0 X1 Y4 Y5" : -0.030753,
"X0 X1 Y6 Y7" : -0.022956,
"X0 X1 Y8 Y9" : -0.022976,
}

In [20]:
def get_Pauli(pauliOp):
    num_qubits = 12
    pauliOp = pauliOp.split()
    num = len(pauliOp)
    pauli_list = ['I'] * (num_qubits)
    if num > 0:
        for item in pauliOp:
            pauli, index = item[0], int(item[1:])
            pauli_list[index] = pauli
    pauli_list = ''.join(pauli_list)

    return pauli_list

In [21]:
num_qubits = 12
pauli_list = []
for pauliOp in data.keys():
    pauli_list.append((get_Pauli(pauliOp), data[pauliOp]))
pauli_list

[('IIIIIIIIIIII', -1.628013),
 ('XXIXZZZZZZXI', -2e-05),
 ('XXIIIIIIIIYY', -0.020966),
 ('XXYYIIIIIIII', -0.030795),
 ('XXYZZZZZZZZY', -2e-05),
 ('XXIIYYIIIIII', -0.030753),
 ('XXIIIIYYIIII', -0.022956),
 ('XXIIIIIIYYII', -0.022976)]